server:
  port: ${SERVER_PORT:8082}

spring.data.mongodb:
  host: ${MONGO_DB_HOST:192.168.2.100}
  database: ${MONGO_DB_NAME:simulation}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    ip-address: ${EUREKA_CLIENT_IP:192.168.1.10}
    non-secure-port: ${EUREKA_CLIENT_PORT:${server.port}}
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      profiles: ${spring.profiles.active}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/


fog:
  simulation:
    registry-url: ubu1604.internal.sintrum.at