server:
  port: ${SERVER_PORT:8080}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    ip-address: ${EUREKA_CLIENT_IP:192.168.1.10}
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management.security.enabled: false
endpoints:
  shutdown:
    enabled: true

fog.metadatamanager: