version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    container_name: fog_logging_elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs:rw
    ports:
      - "49200:9200"
      - "49300:9300"
    environment:
#      - "ES_JAVA_OPTS=\"-Xmx256m -Xms256m\""
      - "xpack.security.enabled=false"
    stdin_open: true
    tty: true
    networks:
      - elk
    restart: always

  elastichq:
    build: elasticsearch-HQ
    container_name: fog_logging_elastichsearch-HQ
    networks:
      - elk
    ports:
       - 49100:80

    restart: always
#  logstash:
#    build: logstash/
#    container_name: fog_logging_logstash
#    volumes:
#      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#    ports:
#      - "45044:5044"
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch

  kibana:
    build: kibana/
    container_name: fog_logging_kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "45601:5601"
    environment:
      - "xpack.security.enabled=false"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always
networks:
  elk:
    driver: bridge
