version: '2'

services:
  eurekaserver:
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  adminserver:
    build:
      context: ./admin-server/
      dockerfile: Dockerfile
    ports:
     - "40080:40080"
    links:
      - "eurekaserver:eureka"
    environment:
      - EUREKA_SERVICE_URL=http://192.168.2.100:8761
      - SERVER_PORT=40080
