version 2:

services:
  eureka-server:
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  admin-server:
    build:
      context: ./admin-server/
      dockerfile: Dockerfile
    ports:
     - "40080:48080"
    link:
      - "eureka-server:eureka"