version: '2'

services:
  eurekaserver:
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  adminserver:
    build:
      context: ./admin-server/
      dockerfile: Dockerfile
    ports:
     - "40080:48080"
    links:
      - "eurekaserver:eureka"
