version: '2'

services:
  eurekaserver:
    container_name: infrastructure_eureka
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
  adminserver:
    container_name: infrastructure_adminserver
    build:
      context: ./admin-server/
      dockerfile: Dockerfile
    ports:
     - "40080:40080"
    links:
      - "eurekaserver:eureka"
    environment:
      - EUREKA_SERVICE_URL=http://192.168.2.100:8761
      - EUREKA_CLIENT_IP=192.168.2.100
      - SERVER_PORT=40080
    restart: always