redis:
  container_name: metadata_redis
  image: redis
  volumes:
    - ./data:/data
  ports:
   - "46379:6379"
redisCommander:
  container_name: metadata_rediscommander
  image: tenstartups/redis-commander
  command: --redis-host redis
  links:
    - redis:redis
  ports:
    - "48081:8081"
